config/routes.rb
Rails.application.routes.draw do
  get 'relationships/create'
  get 'relationships/destroy'
  resources :relationships
  devise_for :users, controllers: { registrations: 'users/registrations', omniauth_callbacks: 'users/omniauth_callbacks' }
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root "tops#hello"
  #resources :tops
  #resources :games
  resources :users
  resources :users do
    member do
      get :following
      get :followers
    end
  end
  resources :matches, :only => [:list, :show, :create, :update]
  get "/about" => "welcomes#index"
  get "/matches/:id/evaluate/:user_id" => "evaluates#index"
  get "/match_list/:year/:section" => "matches#list"
  get "/user/info/edit" => "users#edit"
  put "/user/info/edit" => "users#update"
  get "/user/info/update" => "users#update"
  get "/users/:id/likes" => "users#like"
  post "post_likes" => "likes#create"
  post "post_delete" => "likes#delete"
  
end

app/models/user.rb
class User < ApplicationRecord
  #validates :user_name, presence: true
  attribute :uid, :string, default: SecureRandom.hex(10)
  #belongs_to :match_evaluate, primary_key: :uid, foreign_key: :user_id
  mount_uploader :avatar, AvatarUploader
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable,
         :confirmable, :omniauthable, omniauth_providers: %i[twitter]

  has_many :evaluate_match, dependent: :destroy
  has_many :likes, dependent: :destroy
  has_many :active_relationships, class_name: "Relationship",
                                  foreign_key: "follower_id",
                                  dependent: :destroy
  has_many :passive_relationships, class_name: "Relationship",
                                    foreign_key: "followed_id",
                                    dependent: :destroy

  has_many :following, through: :active_relationships, source: :followed
  has_many :followers, through: :passive_relationships, source: :follower

  validates :user_name, length: { maximum:  15}
  validates :user_name, uniqueness: true
  validates :introduction, length: { maximum:  200}
         
  def self.from_omniauth(auth)
    where(provider: auth.provider, uid: auth.uid).first_or_create do |user|
      user.email = auth.info.email
      user.password = Devise.friendly_token[0,20]
    end
  end

  def update_without_current_password(params, *options)
    params.delete(:current_password)
 
    if params[:password].blank? && params[:password_confirmation].blank?
      params.delete(:password)
      params.delete(:password_confirmation)
    end
 
    result = update(params, *options)
    clean_up_passwords
    result
  end

  def follow(other_user)
    following << other_user
  end

  def unfollow(other_user)
    active_relationships.find_by(followed_id: other_user.id).destroy
  end

  def following?(other_user)
    following.include?(other_user)
  end
  
end

app/controllers/users/confirmations_controller.rb
# frozen_string_literal: true

class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController

    # callback for facebook
    def facebook
      callback_for(:facebook)
    end
  
    # callback for twitter
    def twitter
      callback_for(:twitter)
    end
  
    # callback for google
    def google_oauth2
      callback_for(:google)
    end
  
    # common callback method
    def callback_for(provider)
      @user = User.from_omniauth(request.env["omniauth.auth"])
      if @user.persisted?
        sign_in_and_redirect @user, event: :authentication #this will throw if @user is not activated
        set_flash_message(:notice, :success, kind: "#{provider}".capitalize) if is_navigational_format?
      else
        session["devise.#{provider}_data"] = request.env["omniauth.auth"].except("extra")
        redirect_to new_user_registration_url
      end
    end
  
    def failure
      redirect_to root_path
    end
  
  end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  def update
    self.resource = resource_class.to_adapter.get!(send(:"current_#{resource_name}").to_key)
    prev_unconfirmed_email = resource.unconfirmed_email if resource.respond_to?(:unconfirmed_email)
 
    #if update_resource(resource, account_update_params)
    if resource.update_without_current_password(account_update_params)
      yield resource if block_given?
      if is_flashing_format?
        flash_key = update_needs_confirmation?(resource, prev_unconfirmed_email) ?
          :update_needs_confirmation : :updated
        set_flash_message :notice, flash_key
      end
      sign_in resource_name, resource, :bypass => true
      respond_with resource, :location => after_update_path_for(resource)
    else
      clean_up_passwords resource
      respond_with resource
    end
  end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
   def after_inactive_sign_up_path_for(resource)
     flash[:alert] = "登録したメールアドレスに確認用メールを送信しました。確認用メールから認証を行ってください。"
     root_path
   end

  protected
  # 追記する
  def update_resource(resource, params)
    resource.update_without_current_password(params)
  end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
    include Common
    PER = 10

    def show
      get_match_list(model_name: "evaluate_match")
      @evaluate_ranking = EvaluatePlayer.get_evaluate_ranking(@user)
    end

    def like
      get_match_list(model_name: "like")
    end

    def edit
    end

    def update
      respond_to do |format|
        if @user.update_without_current_password(user_params)
          format.html { redirect_to @user, notice: 'User was successfully updated.' }
          format.json { render :show, status: :ok, location: @user }
        else
          format.html { render :edit }
          format.json { render json: @user.errors, status: :unprocessable_entity }
        end
      end
    end

    def confirmation
    end

    def user_params
      params.permit(:user_name)
    end

    def following
      @user = User.find(params[:id])
      @users = @user.following
      render 'show_follow'
    end

    def followers
      @user = User.find(params[:id])
      @users = @user.followers
      render 'show_follower'
    end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/confirmation.html.haml
%div
  %p
    登録したメールアドレスに、確認用のメールを送信しました。
%div
  %p
    送信メールから本登録行ってください。

app/views/users/edit.html.haml
#main
  = form_with model: @user, :method => :put do |f|
    = f.text_field :user_name
    .circle-avatar
      - if current_user.persisted? && current_user.avatar?
        = image_tag current_user.avatar.to_s
        %label
          = f.check_box :remove_avatar
          画像を削除
      - else
        = image_tag '/assets/icon1.png'
        = f.hidden_field :avatar_cache
      = f.file_field :avatar
  
    = f.submit '更新'

= render "/layouts/sidebar"

app/views/users/like.html.haml
#main
  .user-info-area
    .user-image-area
      %img.user-profile-image{:src => "#{@user.avatar.present? ? @user.avatar.versions[:thumb] : "/assets/icon.jpg"}"}/
    %div
      %p #{@user.user_name}
  
  %a{:href => "/users/#{@user.uid}"}
    ユーザー情報トップ
  %p
    いいね一覧
  
  - @match.zip(@like_count, @evaluate_user).each do |match, like, user|
    .post-info-box
      %a{:href => "/users/#{match.uid}"}
        %img.user-profile-image{:src => "#{user.present? && user.avatar.present? ? user.avatar : "/assets/icon.jpg"}"}/
      %a{:href => "/matches/#{match.match_id}/evaluate/#{match.uid}"}
        .post-info-text
          .post-title J1 第#{match.section}節 #{match.home_team_name} vs #{match.away_team_name}
          .post-info 
            %span by #{match.user_name}
            %span #{match.updated_at.to_s(:time_format)}
            %span
              %i.far.fa-heart
              #{like}

  = paginate @match

= render "/layouts/sidebar"

app/views/users/show.html.haml
#main
  .user-info-area
    .user-image-area
      %img.user-profile-image{:src => "#{@user.avatar.present? ? @user.avatar.versions[:thumb] : "/assets/icon.jpg"}"}/
    %div
      %p #{@user.user_name}
      %div
        = link_to "following: #{@user.following.count}", following_user_path(@user)
        = link_to "followers: #{@user.followers.count}", followers_user_path(@user)
      %a{:href => "/users/#{@user.uid}/likes"}
        %p いいね一覧
  - if @user.introduction.present?
    .user-introduction-area
      %p.user-introduction
        #{@user.introduction}
        
  
  - if @evaluate.present?
    .user-information-analysis
      %canvas.post-teams-analysis
      .post-player-analysis
        %p.post-player-title
          採点プレイヤーランキング
        - @evaluate_ranking.each_with_index do |evaluate, i|
          %p
            %span.rank #{i+1}
            %span.player-name #{evaluate.player_name}
            %span.point #{evaluate.point}
          %p
            %span.team-name #{evaluate.short_name}

  - if current_user.present? && current_user != @user
    - if current_user.following?(@user)
      = form_for(current_user.active_relationships.find_by(followed_id: @user.id), html: { method: :delete }) do |f|
        = f.submit 'Unfollow', :class=>"btn-border"
    - else
      = form_for(current_user.active_relationships.build) do |f|
        %div
          = hidden_field_tag :followed_id, @user.id
        = f.submit "Follow", :class=>"btn-border"

  
  - @match.zip(@like_count, @evaluate_user).each do |match, like, user|
    .post-info-box
      %a{:href => "/users/#{match.uid}"}
        %img.user-profile-image{:src => "#{user.present? && user.avatar.present? ? user.avatar : "/assets/icon.jpg"}"}/
      %a{:href => "/matches/#{match.match_id}/evaluate/#{match.uid}"}
        .post-info-text
          .post-title J1 第#{match.section}節 #{match.home_team_name} vs #{match.away_team_name}
          .post-info 
            %span by #{match.user_name}
            %span #{match.updated_at.to_s(:time_format)}
            %span
              %i.far.fa-heart
              #{like}
  
  = paginate @match

  %input#evaluate_json{:type => "hidden", :value => "#{@evaluate.to_json.html_safe}"}/

= render "/layouts/sidebar"

app/views/users/show_follow.html.haml
#main
  %ul.follow-list
    - @user.following.each do |user|
      %li
        = link_to "#{user.user_name}", user_path(user.uid)
= render "/layouts/sidebar"

app/views/users/show_follower.html.haml
#main
  %ul.follower-list
    - @user.followers.each do |user|
      %li
        = link_to "#{user.user_name}", user_path(user.uid)
= render "/layouts/sidebar"