config/routes.rb
Rails.application.routes.draw do
  get 'relationships/create'
  get 'relationships/destroy'
  resources :relationships
  devise_for :users, controllers: { registrations: 'users/registrations', omniauth_callbacks: 'users/omniauth_callbacks' }
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root "tops#hello"
  #resources :tops
  #resources :games
  resources :users
  resources :users do
    member do
      get :following
      get :followers
    end
  end
  resources :matches, :only => [:list, :show, :create, :update]
  get "/about" => "welcomes#index"
  get "/matches/:id/evaluate/:user_id" => "evaluates#index"
  get "/match_list/:year/:section" => "matches#list"
  get "/user/info/edit" => "users#edit"
  put "/user/info/edit" => "users#update"
  get "/user/info/update" => "users#update"
  get "/users/:id/likes" => "users#like"
  post "post_likes" => "likes#create"
  post "post_delete" => "likes#delete"
  
end

app/models/match.rb
class Match < ApplicationRecord
    belongs_to :evaluate_match, primary_key: :match_id, foreign_key: :match_id 
    belongs_to :home_team, class_name: "Team", primary_key: :home_team_id, foreign_key: :team_id
    belongs_to :away_team, class_name: "Team",primary_key: :away_team_id, foreign_key: :team_id
    has_many :match_info, primary_key: :match_id, foreign_key: :match_id
    has_many :home_team, class_name: "Team", primary_key: :home_team_id, foreign_key: :team_id
    has_many :away_team, class_name: "Team",  primary_key: :away_team_id, foreign_key: :team_id
    has_many :match_player, primary_key: :match_id, foreign_key: :match_id
    has_many :user, through: :evaluate_match
    has_many :like, primary_key: :match_id, foreign_key: :match_id

    scope :get_match_list, -> (section){select("matches.*, teams.short_name as home_team_name ,away_teams_matches.short_name as away_team_name").where(section: section).left_outer_joins(:home_team).left_outer_joins(:away_team).order('matches.id')}
end

app/controllers/matches_controller.rb
class MatchesController < ApplicationController
    before_action :authenticate_user!, except: :list
    include Common

    def list
        @section         = params[:section]
        @latestSection   = Match.maximum("section")
        @nextSection     = @section.to_i + 1 if @section.to_i + 1 <= @latestSection
        @previousSection = @section.to_i - 1 if @section.to_i - 1 >= 1

        @match = Match.get_match_list(@section)
    end

    def show
       get_match_info 
    end

    def create
        #paramsのpermit
        evaluates = params[:evaluate]
        @match_id = request.referer.split("/").last

        registered = EvaluateMatch.where(:user_id => current_user.id, :match_id => @match_id)[0]

        if registered.nil?
          team_ids      = []
          player_ids    = []
          coach_names   = []
          referee_names = []

          # Formの情報を変更されたなどで、試合に関係ない情報が入ってくることを制御
          @team    = MatchInfo.get_match_info(current_user, @match_id)
          @player  = MatchPlayer.get_player_info(current_user, @match_id)
          @coach   = MatchPlayer.get_coach_info(current_user, @match_id)
          @referee = MatchReferee.get_referee_info(current_user, @match_id)

          @team.each do |team|
            team_ids.push(team.team_id)
          end

          @player.each do |player|
            player_ids.push(player.players_player_id)
          end

          @coach.each do |coach|
            coach_names.push(coach.player_name)
          end

          @referee.each do |referee|
            referee_names.push(referee.referee_name)
          end

          begin
            ActiveRecord::Base.connection.transaction do
              EvaluateMatch.create!(:user_id => current_user.id, :match_id => @match_id)
              
              evaluates.each do |evaluate|
                if evaluate[:team_id].present?
                  if team_ids.include?(evaluate[:team_id].to_i)
                    team_ids.delete(evaluate[:team_id].to_i)
                    EvaluateTeam.create!(:user_id => current_user.id, :match_id => @match_id, :team_id => evaluate[:team_id], :evaluate_point => evaluate[:point].present? ? evaluate[:point].to_f : nil , :evaluate_comment => evaluate[:comment])
                  else
                    raise
                  end
                elsif evaluate[:coach_name].present?
                  if coach_names.include?(evaluate[:coach_name])
                    coach_names.delete(evaluate[:coach_name])
                    EvaluateCoach.create!(:user_id => current_user.id, :match_id => @match_id, :coach_name => evaluate[:coach_name], :evaluate_point => evaluate[:point].present? ? evaluate[:point].to_f : nil  )
                  else
                    raise
                  end
                elsif evaluate[:player_id].present?
                  if player_ids.include?(evaluate[:player_id].to_i)
                    player_ids.delete(evaluate[:player_id].to_i)
                    EvaluatePlayer.create!(:user_id => current_user.id, :match_id => @match_id, :player_id => evaluate[:player_id], :evaluate_point => evaluate[:point].present? ? evaluate[:point].to_f : nil  )
                  else
                    raise
                  end
                elsif evaluate[:referee_name].present?
                  if referee_names.include?(evaluate[:referee_name])
                    referee_names.delete(evaluate[:referee_name])
                    EvaluateReferee.create!(:user_id => current_user.id, :match_id => @match_id, :referee_name => evaluate[:referee_name], :evaluate_point => evaluate[:point].present? ? evaluate[:point].to_f : nil  )
                  else
                    raise
                  end
                end
              end
            end

          rescue => e
            logger.info(e.message)
            logger.info("失敗しました")
            flash[:matches_error_message] = e.message
          end
          flash[:alert] = "登録完了しました"
          redirect_to request.referer
        end
    end

    def update
      evaluates = params[:evaluate]
      match_id = request.referer.split("/").last
      team_ids      = []
      player_ids    = []
      coach_names   = []
      referee_names = []

      begin
        ActiveRecord::Base.connection.transaction do
          #update_atのみ更新
          EvaluateMatch.where(user_id: current_user.id)[0].touch
    
          evaluates.each do |evaluate|
            if evaluate[:team_id].present?
              EvaluateTeam.where(user_id: current_user.id, team_id: evaluate[:team_id], match_id: match_id).update(:evaluate_point => evaluate[:point].present? ? evaluate[:point].to_f : nil , :evaluate_comment => evaluate[:comment])
            elsif evaluate[:coach_name].present?
              EvaluateCoach.where(user_id: current_user.id, coach_name: evaluate[:coach_name], match_id: match_id).update(:evaluate_point => evaluate[:point].present? ? evaluate[:point].to_f : nil )
            elsif evaluate[:player_id].present?
              EvaluatePlayer.where(user_id: current_user.id, player_id: evaluate[:player_id], match_id: match_id).update(:evaluate_point => evaluate[:point].present? ? evaluate[:point].to_f : nil  )
            elsif evaluate[:referee_name].present?
              EvaluateReferee.where(user_id: current_user.id, referee_name: evaluate[:referee_name], match_id: match_id).update(:evaluate_point => evaluate[:point].present? ? evaluate[:point].to_f : nil  )
            end
          end
          flash[:alert] = "更新完了しました"
        rescue => e
          logger.info(e)
          logger.info("失敗しました")
          @error_message = e.message
        end
        redirect_to request.referer
      end
    end

end

app/helpers/matches_helper.rb
module MatchesHelper
    def select_point
        return {"-" => "", "0.0" => "0.0", "0.5" => "0.5", "1.0" => "1.0", "1.5" => "1.5", "2.0" => "2.0", "2.5" => "2.5", "3.0" => "3.0", "3.5" => "3.5", "4.0" => "4.0", "4.5" => "4.5", "5.0" => "5.0", "5.5" => "5.5", "6.0" => "6.0", "6.5" => "6.5", "7.0" => "7.0", "7.5" => "7.5", "8.0" => "8.0", "8.5" => "8.5", "9.0" => "9.0", "9.5" => "9.5", "10.0" => "10.0"}
    end

    def selected_evaluate_point(point)
        point.present? ? sprintf( "%.1f", point ) : ""
    end
end

app/views/matches/_evaluate_area.html.haml
#main_title
  #match_title
    %h4
      J1リーグ 第#{@match.section}節
    %p
      = @match.match_date
  
  #team_title
    #home_team
      %p 
        = @homeTeamInfo.short_name
    #score
      #home_score
        %p
          = @homeTeamInfo.first_point.to_i + @homeTeamInfo.second_point.to_i
      #match_result
        %div
          #first_point
            %span 
              = @homeTeamInfo.first_point
            %span 前半
            %span 
              = @awayTeamInfo.first_point
          #second_point
            %span 
              = @homeTeamInfo.second_point
            %span 後半
            %span
              = @awayTeamInfo.second_point
      #away_score
        %p
          = @awayTeamInfo.first_point.to_i + @awayTeamInfo.second_point.to_i
    #away_team
      %a{:href => "javascript:void(0)"} 
        %p 
          = @awayTeamInfo.short_name

= flash[:matches_error_message].gsub(/バリデーションに失敗しました: /, '') if flash[:matches_error_message].present?

.submit-button-area
  = f.submit "登録", :class => "btn-border", :onclick => "doubleStop(this)"

#team_name_info
  .home-member-list.member-list-style
    %ul
      %li.away-team-name.team-name-style{:style => "border-left-color: #{@homeTeamInfo.team_color};"}
        %span.team-name.editable 
          = @homeTeamInfo.short_name
    
  .away-member-list.member-list-style
    %ul
      %li.away-team-name.team-name-style{:style => "border-left-color: #{@awayTeamInfo.team_color};"}
        %span.team-name.editable
          = @awayTeamInfo.short_name

.list-title 
  %span.list-title-style 監督

#coach_name_info
  .home-member-list.member-list-style
    %ul
      %li
        %span.position 監督
        %span.profile-number
        %span.player-name.editable
          = @homeTeamCoach.player_name
        %span.change-time
        %span.player-score
          = f.select "evaluate[][point]", select_point, :selected => selected_evaluate_point(@homeTeamCoach[:evaluate_point]), :include_blank => true
          = f.hidden_field "evaluate[][coach_name]", :value => "#{@homeTeamCoach.player_name}"
        　　
  .away-member-list.member-list-style
    %ul
      %li
        %span.position 監督
        %span.profile-number
        %span.player-name.editable
          = @awayTeamCoach.player_name
        %span.change-time
        %span.player-score
          = f.select "evaluate[][point]", select_point, :selected => selected_evaluate_point(@awayTeamCoach[:evaluate_point]), :include_blank => true
          = f.hidden_field "evaluate[][coach_name]", :value => "#{@awayTeamCoach.player_name}"

.list-title 
  %span.list-title-style スターティングメンバー

#starting_member
  .home-member-list.member-list-style
    %ul
      - @homeTeamPlayer.each do |player|
        %li.home-member-name 
          %span.position 
            = player.position
          %span.profile-number 
            = player.profile_number
          %span.player-name.editable 
            = player.player_name
          %span.change-time 
            = player.player_change
          %span.player-score 
            = f.select "evaluate[][point]", select_point, :selected => selected_evaluate_point(player[:evaluate_point]), :include_blank => true
            = f.hidden_field "evaluate[][player_id]", :value => "#{player[:players_player_id]}"
    
  .away-member-list.member-list-style
    %ul 
      - @awayTeamPlayer.each do |player|
        %li.home-member-name 
          %span.position 
            = player.position
          %span.profile-number 
            = player.profile_number
          %span.player-name.editable 
            = player.player_name
          %span.change-time 
            = player.player_change
          %span.player-score
            = f.select "evaluate[][point]", select_point, :selected => selected_evaluate_point(player[:evaluate_point]), :include_blank => true
            = f.hidden_field "evaluate[][player_id]", :value => "#{player[:players_player_id]}"
.list-title 
  %span.list-title-style 控えメンバー

#substitute_member
  .away-member-list.member-list-style
    %ul
      - @homeTeamSubPlayer.each do |player|
        %li.home-member-name 
          %span.position 
            = player.position
          %span.profile-number 
            = player.profile_number
          %span.player-name.editable 
            = player.player_name
          %span.change-time 
            = player.player_change
          - if player.player_change.present?
            %span.player-score
              = f.select "evaluate[][point]", select_point, :selected => selected_evaluate_point(player[:evaluate_point]), :include_blank => true
              = f.hidden_field "evaluate[][player_id]", :value => "#{player[:players_player_id]}"
    
  .away-member-list.member-list-style
    %ul 
      - @awayTeamSubPlayer.each do |player|
        %li.home-member-name 
          %span.position 
            = player.position
          %span.profile-number 
            = player.profile_number
          %span.player-name.editable 
            = player.player_name
          %span.change-time 
            = player.player_change
          - if player.player_change.present?
            %span.player-score
              = f.select "evaluate[][point]", select_point, :selected => selected_evaluate_point(player[:evaluate_point]), :include_blank => true
              = f.hidden_field "evaluate[][player_id]", :value => "#{player[:players_player_id]}"
      
.list-title 
  %span.list-title-style 審判

#referee_member
  .referee-list.member-list-style
    %ul
      %li.home-member-name 
        %span.position 主審
        %span.player-name
          = @chiefReferee.referee_name
        %span.change-time
        %span.player-score
          = f.select "evaluate[][point]", select_point, :selected => selected_evaluate_point(@chiefReferee[:evaluate_point]), :include_blank => true
          = f.hidden_field "evaluate[][referee_name]", :value => "#{@chiefReferee[:referee_name]}"

      %li.home-member-name 
        %span.position 副審
        %span.player-name
          = @assistantReferee[0].referee_name
        %span.change-time 
        %span.player-score
          = f.select "evaluate[][point]", select_point, :selected => selected_evaluate_point(@assistantReferee[0][:evaluate_point]), :include_blank => true
          = f.hidden_field "evaluate[][referee_name]", :value => "#{@assistantReferee[0].referee_name}"
      %li.home-member-name 
        %span.position 副審
        %span.player-name
          = @assistantReferee[1].referee_name
        %span.change-time 
        %span.player-score
          = f.select "evaluate[][point]", select_point, :selected => selected_evaluate_point(@assistantReferee[1][:evaluate_point]), :include_blank => true
          = f.hidden_field "evaluate[][referee_name]", :value => "#{@assistantReferee[1].referee_name}"

.list-title 
  %span.list-title-style 総評

#overall
  .overall-list
    = f.select "evaluate[][point]", select_point, :selected => selected_evaluate_point(@homeTeamInfo[:evaluate_point]), :include_blank => true
    = f.hidden_field "evaluate[][team_id]", :value => "#{@homeTeamInfo.team_id}"
    = f.text_area "evaluate[][comment]", :value => @homeTeamInfo["evaluate_comment"], :placeholder => "3000字以内で入力してください"

  .overall-list
    = f.select "evaluate[][point]", select_point, :selected => selected_evaluate_point(@awayTeamInfo[:evaluate_point]), :include_blank => true
    = f.hidden_field "evaluate[][team_id]", :value => "#{@awayTeamInfo.team_id}"
    = f.text_area "evaluate[][comment]", :value => @awayTeamInfo["evaluate_comment"], :placeholder => "3000字以内で入力してください"

.submit-button-area
  = f.submit "登録", :class => "btn-border", :onclick => "doubleStop(this)"

.list-title 
  %span.list-title-style 試合詳細

#game_details_area
  %table#game_progress
    %tbody
      - @progress.each do |progress|
        - if progress.progress_type == 0
          %tr
            %td.home_details
              = progress.scorer.present? ? progress.scorer : "オウンゴール" if progress.team_type == 0
              %span.progress-item
                - if progress.team_type == 0
                  %i.far.fa-futbol
            %th 
              = progress.progress_time
              分
            %td.away_details
              %span.progress-item
                - if progress.team_type == 1
                  %i.far.fa-futbol
              = progress.scorer.present? ? progress.scorer : "オウンゴール" if progress.team_type == 1
  
        - elsif progress.progress_type == 1
          %tr
            %td.home_details
              = progress.yellow_card if progress.team_type == 0
              %span.progress-item
                - if progress.team_type == 0
                  %i.fas.fa-square.yellow
            %th 
              = progress.progress_time
              分
            %td.away_details
              %span.progress-item
                - if progress.team_type == 1
                  %i.fas.fa-square.yellow
              = progress.yellow_card if progress.team_type == 1
  
        - elsif progress.progress_type == 2
          %tr
            %td.home_details
              = progress.red_card if progress.team_type == 0
              %span.progress-item
                - if progress.team_type == 0
                  %i.fas.fa-square.red
            %th 
              = progress.progress_time
              分
            %td.away_details
              %span.progress-item
                - if progress.team_type == 1
                  %i.fas.fa-square.red
              = progress.red_card if progress.team_type == 1
  
        - elsif progress.progress_type == 3
          %tr
            %td.home_details
              = progress.red_card if progress.team_type == 0
              %span.progress-item
                - if progress.team_type == 0
                  %i.fas.fa-square.red
            %th 
              = progress.progress_time
              分
            %td.away_details
              %span.progress-item
                - if progress.team_type == 1
                  %i.fas.fa-square.red
              = progress.red_card if progress.team_type == 1
        
        - elsif progress.progress_type == 4
          %tr
            %td.home_details
              - if progress.team_type == 0
                = progress.from_change_player
              %span.progress-item
                - if progress.team_type == 0
                  %i.fas.fa-caret-right
              - if progress.team_type == 0
                = progress.to_change_player
            %th 
              = progress.progress_time
              分
            %td.away_details
              - if progress.team_type == 1
                = progress.from_change_player
              %span.progress-item
                - if progress.team_type == 1
                  %i.fas.fa-caret-right
              - if progress.team_type == 1
                = progress.to_change_player
  
  %table#game_details
    %tbody
      %tr
        %td.home_details
          = @homeTeamInfo.control_rate
        %th ボール支配率
        %td.away_details
          = @awayTeamInfo.control_rate
      %tr
        %td.home_details
          = @homeTeamInfo.shoot_count
        %th シュート
        %td.away_details
          = @awayTeamInfo.shoot_count
      %tr
        %td.home_details
          = @homeTeamInfo.frame_count
        %th 枠内シュート
        %td.away_details 
          = @awayTeamInfo.frame_count
      %tr
        %td.home_details
          = @homeTeamInfo.mileage
        %th 走行距離
        %td.away_details 
          = @awayTeamInfo.mileage
      %tr
        %td.home_details
          = @awayTeamInfo.sprint_count
          杉本 太郎
        %th スプリント
        %td.away_details 
          = @awayTeamInfo.sprint_count
      %tr
        %td.home_details
          = @homeTeamInfo.pass_count
          (#{@homeTeamInfo.pass_success_rate}%)
        %th パス（成功率）
        %td.away_details 
          = @awayTeamInfo.pass_count
          (#{@awayTeamInfo.pass_success_rate}%)
      %tr
        %td.home_details
          = @homeTeamInfo.offside
        %th オフサイド
        %td.away_details 
          = @awayTeamInfo.offside
      %tr
        %td.home_details
          = @homeTeamInfo.freekick_count
        %th フリーキック
        %td.away_details 
          = @awayTeamInfo.freekick_count
      %tr
        %td.home_details
          = @homeTeamInfo.cornerkick_count
        %th コーナーキック
        %td.away_details 
          = @awayTeamInfo.cornerkick_count
      %tr
        %td.home_details
          = @homeTeamInfo.penalty_kick
        %th ペナルティキック
        %td.away_details 
          = @awayTeamInfo.penalty_kick

app/views/matches/list.html.haml
#main
  %ul.other-match-nav
    - if @previousSection.present?
      %li
        %a{:href => "/match_list/2019/#{@section.to_i-1}"}
          %i.fas.fa-chevron-left 
          第#{@section.to_i-1}節
    %li
      第#{@section}節
    - if @nextSection.present?
      %li
        %a{:href => "/match_list/2019/#{@section.to_i+1}"}
          第#{@section.to_i+1}節
          %i.fas.fa-chevron-right
  
  %table
    %thead
      %tr
        %th.date 日時
        %th.home-team-name ホーム
        %th
        %th.away-team-name アウェイ
    %tbody
      - @match.each do |match|
        %tr
          %th
            %a{:href => "/matches/#{match.match_id}"}
              = match.match_date
          %th
            %a{:href => "/matches/#{match.match_id}"}
              = match.home_team_name
          %th
            %a{:href => "/matches/#{match.match_id}"}
              vs
          %th
            %a{:href => "/matches/#{match.match_id}"}
              = match.away_team_name

= render "/layouts/sidebar"

app/views/matches/show.html.haml
#main
  - if flash[:alert].present?
    %div.alert
      = flash[:alert]
  - if @create_flg.present?
    = form_with url: match_path, data: {remote: false}, :method => :put do |f|
      = render "evaluate_area", f: f
  - else
    = form_with url: matches_path, data: {remote: false}, :method => :post do |f|
      = render "evaluate_area", f: f

= render "/layouts/sidebar"